name: Deploy to GitHub Pages

# main ブランチ の push 時にこのワークフローを実行する
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # main ブランチを取得する
      - name: Checkout
        uses: actions/checkout@v4

      # Node.js のセットアップをする
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # パッケージをインストールする
      - name: Install dependencies
        run: npm i --frozen-lockfile

      # ビルドする
      - name: Build
        run: npm run build

      # GitHub Pages にデプロイする
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
